# DB config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##TRAVELMAKER
    password: TRAVELMAKER

  # file upload config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\env\zeesang\kzeesang11-master\

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

# image upload dir
image:
  image-dir: src/main/resources/upload/