# DB config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##TRAVELMAKER
    password: TRAVELMAKER

  # file upload config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
